#!/usr/bin/env python3
"""
Test out-of-scope / unrelated questions: bot should respond that it is only trained
to answer queries related to certain mutual funds and not general queries (no RAG/LLM, no timeout).
Run from repo root: .venv/bin/python3 tests/test_out_of_scope.py
"""
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from Phase4_Backend_API.chat import handle_chat

# Expected substrings in out-of-scope response (rephrased message)
OUT_OF_SCOPE_PHRASE = "only trained to answer"
OUT_OF_SCOPE_PHRASE_ALT = "not general queries"
OUT_OF_SCOPE_MUTUAL = "mutual funds"


def run(query: str, expect_contains: list, expect_refused: bool = False) -> tuple:
    """Run handle_chat(query). Return (passed: bool, message: str)."""
    try:
        out = handle_chat(query)
    except Exception as e:
        return False, f"Exception: {e!r}"
    answer = (out.get("answer") or "").strip()
    source = (out.get("source_url") or "").strip()
    refused = out.get("refused", False)
    audit_path = out.get("audit_path", "")

    if refused != expect_refused:
        return False, f"refused={refused} expected {expect_refused}"
    if not answer:
        return False, "empty answer"
    if audit_path != "out_of_scope":
        return False, f"expected audit_path=out_of_scope, got {audit_path!r}"
    for sub in expect_contains:
        if sub.lower() not in answer.lower():
            return False, f"answer missing '{sub}': {answer[:120]!r}..."
    if source:
        return False, f"out_of_scope should have no source link, got source_url={source!r}"
    return True, "OK"


# Sample from the user's long list of out-of-scope questions (closest match should trigger)
USER_OUT_OF_SCOPE_SAMPLES = [
    "What documents are needed for a passport?",
    "What's the difference between HTTP and TCP?",
    "Who wrote 'The Alchemist'?",
    "How do I organize my closet?",
    "Will it rain in Pune tomorrow?",
    "Suggest family-friendly shows to watch.",
    "How do I prepare for monsoon in Pune?",
    "What is the difference between high court and supreme court?",
    "How do I fix error code 404 on Google Drive?",
    "How does GPS work?",
    "How do I fix this JavaScript error: SyntaxError?",
    "Best places to visit near Indore in a weekend?",
    "How do I get from Lucknow airport to city center?",
    "How do I clean my laptop screen safely?",
    "How do I build a LinkedIn profile for software engineer?",
    "Share a quick recipe for mushrooms.",
    "How do I use Git to resolve merge conflicts?",
    "How do I get rid of cockroaches?",
    "Is there a heatwave expected in Kochi this week?",
    "Suggest budget hotels in Hyderabad.",
    "Who is Isaac Newton?",
    "How do I recover deleted files on OnePlus phone?",
    "What documents are needed for a driving license?",
    "Who won the FIFA World Cup in 2022?",
    "How do I register a complaint online?",
    "How many calories are in chicken breast?",
    "What is the tallest mountain in Europe?",
    "How do I back up my photos to the cloud?",
    "Suggest 5 books like 'Atomic Habits'.",
    "How do I clear cache on Samsung phone?",
    "How do I write a resume for software engineer?",
    "What's the current GST rate on electronics?",
    "How do I meal prep for 5 days?",
    "Give me an example of observer pattern in Python.",
    "How long should I cook eggs?",
    "What's the UV index in Nagpur tomorrow?",
    "Who is Marie Curie?",
    "How do I reset my Facebook password?",
    "How do I remove coffee stain from a jeans?",
    "Best time to book flights to Chennai?",
    "What does neural network mean?",
    "How do I organize my kitchen?",
    "Who won the Wimbledon in 2020?",
    "How do I improve my English speaking?",
    "How do I reset my WhatsApp password?",
    "How do I apply for a PAN card in India?",
    "Plan a 2-day itinerary for Goa.",
    "Tell me a joke about cats.",
    "What's the difference between array and linked list?",
    "How do I recover deleted files on MacBook?",
    "How can I reduce fever at home?",
    "Explain what recursion is.",
    "Explain the rules of tennis.",
    "How do I use Git to revert a commit?",
    "Write a Python function to parse JSON.",
    "Suggest breakfast ideas for vegetarian.",
    "What is the tallest mountain in the world?",
    "Why is my MacBook running slow?",
    "What are the top songs by AR Rahman?",
    "Why did my chocolate cake turn out too dry?",
    "How do I make pasta at home?",
    "How do I make idli at home?",
    "How do I optimize a SQL query?",
    "Recommend podcasts about the solar system.",
    "How do I recover deleted files on iPhone?",
    "What are symptoms of dengue?",
    "What's the tips to save electricity at home?",
    "Tell me a joke about office life.",
    "How do I set up Kubernetes on Windows?",
    "Who wrote 'Harry Potter'?",
    "Explain cybercrime reporting in simple terms.",
    "How do I clear cache on Android phone?",
    "What's the difference between RAM and storage?",
    "How do I use Git to stash changes?",
    "What documents are needed for a PAN card?",
    "Explain the rules of tennis.",
    "Suggest a beginner workout plan for better posture.",
    "What is the tallest mountain in India?",
    "When did World War II happen?",
    "How long should I cook quinoa?",
    "How do I bake cookies without eggs?",
    "How do I fix a noisy ceiling fan?",
    "Why did my paneer butter masala turn out undercooked?",
    "How do I deploy a Next.js app?",
    "Is it safe to take ibuprofen daily?",
    "How do I prepare for an interview for software engineer?",
    "How do I deploy a React app?",
    "What should I pack for Mumbai in December?",
    "Why is my OnePlus phone running slow?",
    "Who is Albert Einstein?",
    "How do I deploy a Flask app?",
    "Why is the sky blue?",
    "Explain black holes in simple terms.",
    "What are common finance interview questions?",
    "When did the French Revolution happen?",
    "Explain what a queue is.",
    "What's the difference between 4G and 5G?",
    "How long should I cook rice?",
    "What are symptoms of flu?",
    "How many calories are in paneer?",
    "How do I get from Ahmedabad airport to city center?",
    "What are the best games on PC?",
    "Plan a 5-day itinerary for Ahmedabad.",
    "Explain inflation in simple terms.",
    "What is the capital of Germany?",
    "Recommend podcasts about volcanoes.",
    "How do I make paneer butter masala at home?",
    "Suggest 5 books like 'Harry Potter'.",
    "Is it safe to take vitamin D daily?",
    "Explain what REST is.",
    "Who won the Wimbledon in 2019?",
    "Why is my iPhone running slow?",
    "What does metaverse mean?",
    "Tell me a joke about food.",
    "What are stretches for neck pain?",
    "How do I write a resume for accountant?",
    "How do I deal with burnout at work?",
    "Who wrote 'To Kill a Mockingbird'?",
    "What's the difference between SSD and HDD?",
    "Share a quick recipe for chickpeas.",
    "When did the Moon landing happen?",
    "What's the difference between class and object?",
    "How do I store milk to keep it fresh?",
    "Explain time complexity of binary search.",
    "Who is Leonardo da Vinci?",
    "How do I clear cache on OnePlus phone?",
    "Why did my pasta turn out too spicy?",
    "What is the capital of Japan?",
    "Who won the NBA Finals in 2022?",
    "How do I fix error code 404 on PhonePe?",
    "What's the difference between Wi-Fi and Bluetooth?",
    "How does a microwave work?",
    "Why is the sky red?",
    "Explain consumer rights in simple terms.",
    "Give me 5 facts about the internet.",
    "Write a Java function to sort a list of numbers.",
    "Recommend hidden gems in Hyderabad.",
    "What's the best season to visit Jaipur?",
    "Suggest budget hotels in Pune.",
    "Explain time complexity of binary search.",
    "How do I clear cache on OnePlus phone?",
    "What is the capital of Australia?",
    "Why is humidity so high in Visakhapatnam this evening?",
    "Recommend hidden gems in Kolkata.",
    "Who wrote 'The Hobbit'?",
    "How do I get from Indore airport to city center?",
    "What is the capital of Peru?",
    "How do I meal prep for 2 days?",
    "What is the process to update PAN details?",
    "Write a Java function to read a CSV file.",
    "Best places to visit near Goa in a weekend?",
    "Who won the FIFA World Cup in 2018?",
    "What should I pack for Kolkata in March?",
    "How do I update Windows 10?",
    "Tell me a joke about school.",
    "What's the difference between HTTP and HTTPS?",
    "What is the plot of 3 Idiots?",
    "Write a C++ function to reverse a string.",
    "How do I deploy a Spring Boot app?",
    "Explain time complexity of BFS.",
    "How do I prepare for monsoon in Lucknow?",
    "What is the capital of Indonesia?",
    "Best places to visit near Bengaluru in a weekend?",
    "How do I get from Goa airport to city center?",
    "Why did my dal tadka turn out burnt?",
    "How much does a trip to Bengaluru cost for 10 days?",
    "What is the capital of South Africa?",
    "Will it rain in Delhi today?",
    "What's a good meal plan for vegetarian?",
    "Who won the FIFA World Cup in 2020?",
    "Which local foods should I try in Guwahati?",
    "How cold will it get in Ahmedabad tonight?",
    "How do I fix this Go error: TypeError: undefined is not a function?",
    "Who wrote '1984'?",
    "How do I remove oil stain from a jeans?",
    "What should I pack for Chennai in October?",
    "How do I bake brownies without eggs?",
    "How do I make biryani at home?",
    "Recommend hidden gems in Bengaluru.",
    "Who won the Asia Cup in 2013?",
    "How do I apply for a Aadhaar in India?",
    "What is the capital of Norway?",
    "When did the Industrial Revolution happen?",
    "What should I pack for Guwahati in August?",
    "What's the air quality index in Hyderabad this weekend?",
    "Is there a heatwave expected in Delhi this week?",
    "What is the capital of Spain?",
    "Will it rain in Ahmedabad next week?",
    "How do I apply for a driving license in India?",
    "Is Ahmedabad safe to travel solo?",
    "How much does a trip to Surat cost for 3 days?",
    "Write a C++ function to parse JSON.",
    "How do I prepare for monsoon in Indore?",
    "Best places to visit near Nagpur in a weekend?",
    "Why is humidity so high in Jaipur this evening?",
    "Will it rain in Kochi today?",
    "What's the UV index in Ahmedabad tomorrow?",
    "How cold will it get in Lucknow tonight?",
    "Suggest snacks ideas for vegetarian.",
    "How do I fix error code 403 on Paytm?",
    "Best places to visit near Bhopal in a weekend?",
    "How can I reduce headache at home?",
    "Who won the FIFA World Cup in 2025?",
    "How do I get from Surat airport to city center?",
    "How much does a trip to Pune cost for 6 days?",
    "What is the capital of Egypt?",
    "Write a TypeScript function to read a CSV file.",
    "Best time to book flights to Coimbatore?",
    "How much does a trip to Goa cost for 10 days?",
    "What's a healthy substitute for lentils?",
    "What are the top songs by Taylor Swift?",
    "What's the air quality index in Bengaluru right now?",
    "Is Kolkata safe to travel solo?",
    "Which local foods should I try in Goa?",
    "Who won the FIFA World Cup in 2009?",
    "Recommend hidden gems in Nagpur.",
    "What should I pack for Guwahati in December?",
    "What's the air quality index in Surat tomorrow?",
    "Write a Java function to call a REST API.",
    "Give me an example of singleton in TypeScript.",
    "How do I get from Bengaluru airport to city center?",
    "What's the best season to visit Indore?",
    "Write a TypeScript function to validate an email.",
    "Will it rain in Nagpur right now?",
    "Write a Go function to read a CSV file.",
    "Plan a 6-day itinerary for Guwahati.",
    "What should I pack for Hyderabad in August?",
    "Will it rain in Surat today?",
    "Write a Java function to validate an email.",
    "What's the weather like in Coimbatore this weekend?",
    "Which local foods should I try in Mumbai?",
    "Give me a grocery list for South Indian dinner.",
    "What is the capital of Canada?",
    "How much does a trip to Bhopal cost for 10 days?",
    "Why is humidity so high in Surat right now?",
    "What's the best season to visit Visakhapatnam?",
    "How much does a trip to Nagpur cost for 2 days?",
    "Write a TypeScript function to reverse a string.",
    "How do I deploy a Spring Boot app?",
    "Who won the NBA Finals in 2020?",
    "How do I set up Docker on Windows?",
    "Will it rain in Mumbai next week?",
    "Best time to book flights to Hyderabad?",
    "How do I remove coffee stain from a white bedsheet?",
    "How do I remove coffee stain from a cotton shirt?",
    "How do I fix this Python error: SyntaxError?",
    "Is there a cyclone alert near Indore?",
    "What are symptoms of COVID-19?",
    "Plan a 2-day itinerary for Delhi.",
    "What's the best season to visit Chennai?",
    "What should I pack for Kochi in November?",
    "Is there a heatwave expected in Mumbai this week?",
    "Suggest budget hotels in Nagpur.",
    "What's the air quality index in Surat right now?",
    "What's the air quality index in Bengaluru this weekend?",
    "What should I pack for Guwahati in March?",
    "Why is humidity so high in Kolkata this weekend?",
    "What's the air quality index in Hyderabad right now?",
    "What's the weather like in Kolkata today?",
    "Why is humidity so high in Kolkata right now?",
    "Is there a heatwave expected in Hyderabad this week?",
    "When did the Renaissance happen?",
    "Will it rain in Bengaluru this evening?",
    "Why is humidity so high in Bengaluru this weekend?",
    "How many calories are in egg?",
    "How do I fix a mold on walls?",
    "What's the UV index in Bhopal this weekend?",
    "Who won the FIFA World Cup in 2018?",
    "What should I pack for Visakhapatnam in December?",
    "How do I fix error code 404 on WhatsApp?",
    "Best places to visit near Kolkata in a weekend?",
    "What's the air quality index in Lucknow this weekend?",
    "How cold will it get in Visakhapatnam tonight?",
    "How do I fix error code 404 on Outlook?",
    "What are symptoms of food poisoning?",
    "How do I fix error code E101 on Paytm?",
    "What's the UV index in Visakhapatnam this weekend?",
    "What's the air quality index in Jaipur this weekend?",
    "Which local foods should I try in Surat?",
    "How do I get from Nagpur airport to city center?",
    "What's the UV index in Lucknow next week?",
    "What's the UV index in Kochi this evening?",
    "Will it rain in Ahmedabad tomorrow?",
    "Plan a 10-day itinerary for Surat.",
    "Plan a 6-day itinerary for Nagpur.",
    "Write a Python function to read a CSV file.",
    "Will it rain in Chennai right now?",
    "Recommend hidden gems in Mumbai.",
    "Who won the FIFA World Cup in 2017?",
    "Is Kochi safe to travel solo?",
    "Suggest lunch ideas for low-carb.",
    "What should I pack for Lucknow in March?",
    "Why did my dal tadka turn out too spicy?",
    "Will it rain in Bengaluru today?",
    "Best time to book flights to Surat?",
    "Why did my fried rice turn out burnt?",
    "What's the air quality index in Coimbatore right now?",
    "How do I fix this C++ error: IndexError?",
    "Which local foods should I try in Hyderabad?",
    "Write a TypeScript function to call a REST API.",
    "Give me an example of factory pattern in C++.",
    "What's the UV index in Visakhapatnam next week?",
    "How do I prepare for monsoon in Kolkata?",
    "How do I fix error code 403 on Google Drive?",
    "How much does a trip to Pune cost for 2 days?",
    "What's the UV index in Jaipur right now?",
    "How much does a trip to Pune cost for 4 days?",
    "Why did my sambar turn out undercooked?",
    "Why is humidity so high in Bengaluru right now?",
    "What should I pack for Surat in December?",
    "What's the air quality index in Chandigarh right now?",
    "How do I fix this TypeScript error: KeyError?",
    "What's the weather like in Coimbatore right now?",
    "What's the UV index in Jaipur tomorrow?",
    "What's the UV index in Nagpur this evening?",
    "Suggest budget hotels in Kochi.",
    "What's the UV index in Hyderabad next week?",
    "What should I pack for Surat in August?",
    "Best time to book flights to Guwahati?",
    "How do I fix this JavaScript error: IndexError?",
    "Plan a 3-day itinerary for Pune.",
    "Who won the NBA Finals in 2022?",
    "How do I remove grass stain from a cotton shirt?",
    "Give me an example of factory pattern in JavaScript.",
    "Plan a 10-day itinerary for Pune.",
    "Will it rain in Kolkata tomorrow?",
    "What should I pack for Guwahati in November?",
    "What's the air quality index in Kochi right now?",
    "Who won the NBA Finals in 2016?",
    "Give me an example of strategy pattern in TypeScript.",
    "How many calories are in banana?",
    "Why did my fried rice turn out too salty?",
    "What is the capital of Japan?",
    "How cold will it get in Jaipur tonight?",
    "Plan a 5-day itinerary for Hyderabad.",
    "Who won the IPL in 2018?",
    "How do I fix error code 404 on PhonePe?",
    "Best places to visit near Lucknow in a weekend?",
    "What's the air quality index in Chennai this evening?",
    "Why is humidity so high in Kochi this evening?",
    "Why is humidity so high in Nagpur tomorrow?",
    "How do I prepare for monsoon in Goa?",
    "How much does a trip to Kochi cost for 5 days?",
    "Why is humidity so high in Goa tomorrow?",
    "How do I get from Chennai airport to city center?",
    "What should I pack for Mumbai in July?",
    "What's the air quality index in Coimbatore this evening?",
    "How do I fix error code 500 on Gmail?",
    "What's the UV index in Lucknow tomorrow?",
    "Recommend hidden gems in Kochi.",
    "Is there a heatwave expected in Indore this week?",
    "Which local foods should I try in Visakhapatnam?",
    "What's the best season to visit Bengaluru?",
    "Plan a 7-day itinerary for Guwahati.",
    "What's the weather like in Chennai this weekend?",
    "How do I fix error code 500 on Facebook?",
    "Will it rain in Lucknow today?",
    "How do I clear cache on iPhone?",
    "What's the air quality index in Indore right now?",
    "How do I get from Pune airport to city center?",
    "Why is humidity so high in Visakhapatnam tomorrow?",
    "Which local foods should I try in Nagpur?",
    "What's the UV index in Kochi this weekend?",
    "How do I fix error code ERR_CONNECTION_RESET on Facebook?",
    "What's the air quality index in Chennai this weekend?",
    "Why is humidity so high in Surat today?",
    "Suggest lunch ideas for keto.",
    "Is Pune safe to travel solo?",
    "How do I meal prep for 10 days?",
    "Why did my idli turn out too dry?",
    "How do I remove wine stain from a cotton shirt?",
    "What's the best season to visit Mumbai?",
    "What should I pack for Indore in June?",
    "What's the weather like in Jaipur today?",
    "Draft an email to apologize for a delay.",
    "Why is humidity so high in Mumbai today?",
    "Plan a 2-day itinerary for Bhopal.",
    "How much does a trip to Kolkata cost for 2 days?",
    "Will it rain in Pune next week?",
    "Why is humidity so high in Hyderabad this weekend?",
    "Suggest lunch ideas for vegetarian.",
    "How do I enable two-factor authentication on Instagram?",
    "Is there a cyclone alert near Bhopal?",
    "Who won the NBA Finals in 2013?",
    "Best places to visit near Visakhapatnam in a weekend?",
    "What's the air quality index in Surat today?",
    "How do I fix error code ERR_CONNECTION_RESET on Instagram?",
    "What should I pack for Visakhapatnam in April?",
    "Why did my biryani turn out too dry?",
    "What's the UV index in Mumbai right now?",
    "Write a Go function to validate an email.",
    "How do I make chocolate cake at home?",
    "How do I fix error code 500 on PhonePe?",
    "What is the capital of Australia?",
    "Why is humidity so high in Visakhapatnam this evening?",
    "Recommend hidden gems in Kolkata.",
    "Is there a cyclone alert near Coimbatore?",
    "Plan a 6-day itinerary for Chennai.",
    "Who won the IPL in 2009?",
    "Which local foods should I try in Bhopal?",
    "Which local foods should I try in Pune?",
    "Will it rain in Indore tomorrow?",
    "Write a TypeScript function to parse JSON.",
    "How much does a trip to Visakhapatnam cost for 2 days?",
    "Why is humidity so high in Indore tomorrow?",
    "Why did my sambar turn out too salty?",
    "What's the air quality index in Jaipur tomorrow?",
    "Write a JavaScript function to call a REST API.",
    "Explain blockchain in simple terms.",
    "How do I reset my Outlook password?",
    "How do I fix error code 403 on WhatsApp?",
    "Why is humidity so high in Pune today?",
    "How much does a trip to Guwahati cost for 2 days?",
    "Why is humidity so high in Pune tomorrow?",
    "What's the air quality index in Guwahati this weekend?",
    "What is the capital of France?",
    "Who won the Wimbledon in 2009?",
    "Is Jaipur safe to travel solo?",
    "Who won the NBA Finals in 2015?",
    "Will it rain in Mumbai right now?",
    "What's the air quality index in Ahmedabad today?",
    "What's the weather like in Hyderabad this evening?",
    "Plan a 3-day itinerary for Guwahati.",
    "Why did my idli turn out too spicy?",
    "How cold will it get in Coimbatore tonight?",
    "Will it rain in Visakhapatnam today?",
    "What's the air quality index in Lucknow tomorrow?",
    "Suggest budget hotels in Delhi.",
    "Why is humidity so high in Bhopal tomorrow?",
    "How much does a trip to Bengaluru cost for 7 days?",
    "Why is humidity so high in Kolkata this evening?",
    "What should I pack for Surat in June?",
    "How cold will it get in Bhopal tonight?",
    "Is there a cyclone alert near Ahmedabad?",
    "Plan a 10-day itinerary for Chennai.",
    "Recommend hidden gems in Surat.",
    "Is Bhopal safe to travel solo?",
]

EXPECT_CONTAINS = [OUT_OF_SCOPE_PHRASE, OUT_OF_SCOPE_MUTUAL]


def main():
    failed = []
    # Original regex-based cases
    cases = [
        ("US Dollar Price", EXPECT_CONTAINS, False),
        ("What is the US Dollar Price?", EXPECT_CONTAINS, False),
        ("Dollar price today", [OUT_OF_SCOPE_PHRASE], False),
        ("Weather in Mumbai", [OUT_OF_SCOPE_PHRASE], False),
        ("Who won the cricket match?", [OUT_OF_SCOPE_PHRASE], False),
        ("Gold price", [OUT_OF_SCOPE_PHRASE], False),
        ("Stock price of Reliance", [OUT_OF_SCOPE_PHRASE], False),
        ("Give me a recipe for pasta", EXPECT_CONTAINS, False),
    ]
    for query, expect_contains, expect_refused in cases:
        ok, msg = run(query, expect_contains, expect_refused)
        if not ok:
            failed.append(f"  Query: {query!r} -> {msg}")
        else:
            print(f"  OK: {query!r}")

    # Sample from user's long list (phrase-based / closest match)
    for query in USER_OUT_OF_SCOPE_SAMPLES:
        ok, msg = run(query, EXPECT_CONTAINS, False)
        if not ok:
            failed.append(f"  Query: {query!r} -> {msg}")
        else:
            print(f"  OK: {query!r}")

    if failed:
        print("FAILED:", len(failed))
        for f in failed[:30]:
            print(f)
        if len(failed) > 30:
            print(f"  ... and {len(failed) - 30} more")
        sys.exit(1)
    print("All out-of-scope tests passed.")


if __name__ == "__main__":
    main()
